### PR TITLE
set enable additional boundary vertices to false

### LINKED ISSUE #165: Surface meter generation undefined in 3D using point bundles
During `reinit_tria` in `SurfaceMeter`, the `place_additional_boundary_vertices` flag is automatically set to `true` for generating meshes from point bundles. In 3-dimensions when this is passed to `triangulate_segments` in `surface_tria.h`, Steiner points are generated which resets the boundary vertex numbering such that the boundary condition definition in `fit_boundary_vertices` is no longer defined as the Steiner points do not have a position to be fit to unlike the original vertices.

### PR DESCRIPTION
**Pull request by marshallrdavey**
fixes #165

### CODE REVIEW

**Comment by marshallrdavey** [comment]
@drwells I can add a simple test that outputs the final boundary vertices' locations if needed

**Comment by drwells** [comment]
Yup, we definitely need a test since we fixed a bug.

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
This looks good - do you plan on changing anything else?

**Comment by marshallrdavey** [comment]
Nope, I can rebase if you want.

**Comment by drwells** [comment]
Nah.

**Pull request merged**
